### ISSUE TITLE
Single Pass VR

### ISSUE THREAD

**Issue by Snooba** [Haruma-K/URPGrabPass#1]
Hello! Thanks for this! I have an issue currently, and it's that if this package is applied to a Single Pass render VR project, the screen will be gray on one eye on startup. The grabpass shader works correctly in the editor, so that is set up correctly.

Do you have any ideas?

**Comment by Haruma-K** [comment]
Sorry I can' t check because I don't have a VR development environment. Is it possible to reproduce this in the editor using the MockHMD XR Plugin or similar?
And I want to know your Unity version.

**Comment by Snooba** [comment]
Sadly no, the Mock HMD plugin doesn't have this issue.

**Comment by Haruma-K** [comment]
I cannot support VR devices in my development environment, so I will make it unsupported. Sorry.
