### ISSUE TITLE
Support for 2022.1?

### ISSUE THREAD

**Issue by CanopyMatt** [Haruma-K/URPGrabPass#2]
I'm getting following error in 2022.1 - any idea?

`You can only call cameraColorTarget inside the scope of a ScriptableRenderPass. Otherwise the pipeline camera target texture might have not been created or might have already been disposed.`

**Comment by Haruma-K** [comment]
@canopymatt 
Reproduced. Thanks for your report.
I fixed this issue and published 1.0.6.
Please update your version and try it.

https://github.com/Haruma-K/URPGrabPass/releases/tag/1.0.6

**Comment by CanopyMatt** [comment]
@Haruma-K thank you so much for the quick fix! This is a very helpful package for my project.
